test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials:
    type: "service_account"
    project_id: <%= Rails.application.credentials.dig(:gcskey, :project_id) %>
    private_key_id: <%= Rails.application.credentials.dig(:gcskey, :private_key_id) %>
    private_key: <%= Rails.application.credentials.dig(:gcskey, :private_key).dump %>
    client_email: <%= Rails.application.credentials.dig(:gcskey, :client_email) %>
    client_id: <%= Rails.application.credentials.dig(:gcskey, :client_id) %>
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: <%= Rails.application.credentials.dig(:gcskey, :client_x509_cert_url) %>
  project: "phd-palchykov"
  bucket: "phd-palchykov-storage"
  public: true
